theme: minima
title: Welcome to my website!
author: Kennan Guan
email: kennanguan722@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Kennan Guan

# social links
instagram_username: kennan_guan # DO NOT include the @ character, or else the build will fail!
linkedin_username: Kennan-Guan
github_username:  kguan28 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
